import os
from fastapi import FastAPI
from pydantic import BaseModel

try:
    import requests
except ImportError:
    requests = None 

app = FastAPI()

class LLMRequest(BaseModel):
    prompt: str

# Use an environment variable to identify the node (e.g., STABLE_PROD or CANDIDATE_TEST)
NODE_NAME = os.getenv("NODE_ENV", "unknown-node")

# Address for Ollama running on your Mac (host.docker.internal works from inside Docker)
OLLAMA_URL = "http://host.docker.internal:11434/api/generate"

@app.post("/predict")
async def predict(request: LLMRequest):
    try:
        # Direct pass-through to Llama3 (or your preferred model)
        # No extra storage or databases involved
        response = requests.post(
            OLLAMA_URL,
            json={
                "model": "llama3", 
                "prompt": request.prompt, 
                "stream": False
            },
            timeout=30  # Gives the LLM time to think
        )
        response.raise_for_status()
        
        # Extract the actual text generated by the AI
        ai_text = response.json().get("response", "No response from LLM")

        return {
            "model_output": ai_text,
            "node_identity": NODE_NAME,
            "status": "online"
        }

    except Exception as e:
        return {
            "model_output": f"Error connecting to LLM: {str(e)}",
            "node_identity": NODE_NAME,
            "status": "error"
        }